name: Python application test with Poetry

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
      
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      env:
        POETRY_VERSION: 1.7.1  # Specify the version of Poetry you want to use
      run: |
        curl -sSL https://install.python-poetry.org | python3 - --version $POETRY_VERSION
      
    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |
        poetry install

    - name: Run pytest
      run: |
        poetry run pytest

